apiVersion: v1
kind: Service
metadata:
  name: postgresqlservice #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: postgresql
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 5462 #Service port
    targetPort: 5462 #The port for the postgresql container
